//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanesDeViajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_Detalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plan_Detalle()
        {
            this.Reservaciones = new HashSet<Reservaciones>();
        }
    
        public int IdDetalle { get; set; }
        public Nullable<int> IdHotel { get; set; }
        public Nullable<int> IdPlan { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Hoteles Hoteles { get; set; }
        public virtual Planes Planes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservaciones> Reservaciones { get; set; }
    }
}
